name: KiCad

on:
  pull_request:
    paths:
      - "**/*.kicad_pcb"
      - "**/*.kicad_sch"

permissions:
  contents: read
  pull-requests: write

env:
  KICAD_IMAGE: "kicad/kicad:10.0"

jobs:

  kicad_actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Pull KiCad Docker Image
        run: docker pull "$KICAD_IMAGE"

      - name: Run ERC for planewatcher
        run: |
          docker run -v "$GITHUB_WORKSPACE":/workspace "$KICAD_IMAGE" \
            kicad-cli sch erc \
              --severity-error \
              --severity-warning \
              --exit-code-violations \
              --output /workspace/planewatcher/kicad/planewatcher_erc.rpt \
              /workspace/planewatcher/kicad/planewatcher.kicad_sch
          cat ./planewatcher/kicad/planewatcher_erc.rpt

      - name: Run DRC for planewatcher
        run: |
          docker run -v "$GITHUB_WORKSPACE":/workspace "$KICAD_IMAGE" \
            kicad-cli pcb drc \
              --severity-error \
              --severity-warning \
              --all-track-errors \
              --schematic-parity \
              --refill-zones \
              --exit-code-violations \
              --output /workspace/planewatcher/kicad/planewatcher_drc.rpt \
              /workspace/planewatcher/kicad/planewatcher.kicad_pcb
          cat ./planewatcher/kicad/planewatcher_drc.rpt

  kicadiff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: sksat/kicadiff@v0.1.1
        with:
          path: planewatcher/kicad/
          upload-artifact: "true"
          pr-comment: "true"
          pr-description: "true"